[tool.poetry]
name = "pasman"
version = "0.1.0"
description = ""
authors = ["griezly <daniltk.yandex.ru@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
